In [1]:
import pandas as pd

# 파일 경로
date_file = "date_dataset.csv"
time_file = "time_dataset.csv"
# CSV 파일 불러오기
date = pd.read_csv(date_file)
time = pd.read_csv(time_file)

C:\Users\haeun\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\haeun\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
date

,USE_DT,BUS_ROUTE_ID,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,RIDE_PASGR_NUM,ALIGHT_PASGR_NUM,WORK_DT
0,20231101,11110001,100,100번(하계동~용산구청),100000003,01003,명륜3가.성대입구(00030),176,185,20231104
1,20231101,11110001,100,100번(하계동~용산구청),101000057,02156,을지로입구.로얄호텔(00079),171,148,20231104
2,20231101,11110001,100,100번(하계동~용산구청),101000060,02159,을지로2가.파인에빈뉴(00080),236,98,20231104
3,20231101,11110001,100,100번(하계동~용산구청),102000173,03267,서빙고역교차로(00062),42,32,20231104
4,20231101,11110001,100,100번(하계동~용산구청),101000061,02160,을지로3가(00035),95,341,20231104
...,...,...,...,...,...,...,...,...,...,...
7410223,20240430,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000180,14271,월드컵파크7단지(00010),13,72,20240503
7410224,20240430,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000202,14296,디지털미디어시티역2번출구(00001),127,0,20240503
7410225,20240430,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000204,14307,누리꿈스퀘어.MBC(00005),62,40,20240503
7410226,20240430,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000450,14359,공항철도디지털미디어시티역(00015),0,77,20240503
7410227,20240430,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000452,14357,SBS.YTN(00014),25,36,20240503

In [3]:
time

,USE_MON,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MIDNIGHT_RIDE_NUM,MIDNIGHT_ALIGHT_NUM,ONE_RIDE_NUM,ONE_ALIGHT_NUM,...,TWENTY_ALIGHT_NUM,TWENTY_ONE_RIDE_NUM,TWENTY_ONE_ALIGHT_NUM,TWENTY_TWO_RIDE_NUM,TWENTY_TWO_ALIGHT_NUM,TWENTY_THREE_RIDE_NUM,TWENTY_THREE_ALIGHT_NUM,MNTN_TYP_CD,MNTN_TYP_NM,WORK_DT
0,202301,100,100번(하계동~용산구청),110000327,11428,한성여객종점(00001),0,2,0,2,...,0,5,2,3,2,0,0,10,서울간선버스,20230203
1,202301,100,100번(하계동~용산구청),110000335,11436,하계1동주민센터(00010),0,0,0,0,...,36,135,29,150,37,0,0,10,서울간선버스,20230203
2,202301,100,100번(하계동~용산구청),107000011,08101,숭곡초교입구(00100),149,98,16,24,...,243,247,233,158,308,135,192,10,서울간선버스,20230203
3,202301,100,100번(하계동~용산구청),107000012,08102,창문여고(00101),167,220,27,33,...,425,300,491,282,503,196,303,10,서울간선버스,20230203
4,202301,100,100번(하계동~용산구청),107000013,08103,동방고개(00102),11,151,6,32,...,176,45,173,28,204,21,164,10,서울간선버스,20230203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669580,202404,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000204,14307,누리꿈스퀘어.MBC(00005),0,0,0,0,...,2,0,0,0,0,0,0,20,서울지선버스,20240503
669581,202404,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),0,0,0,0,...,0,0,0,0,0,0,0,20,서울지선버스,20240503
669582,202404,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000181,14272,월드컵파크7단지(00007),0,0,0,0,...,6,0,0,0,0,0,0,20,서울지선버스,20240503
669583,202404,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000040,16136,가양역.마포중고등학교(00008),0,0,0,0,...,160,0,0,0,0,0,0,20,서울지선버스,20240503
669584,202404,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000039,16135,가양역.마포중고등학교(00009),0,0,0,0,...,4,0,0,0,0,0,0,20,서울지선버스,20240503

### 데이터 탐구

In [4]:
time['USE_MON'].value_counts()

202310    42438
202402    42370
202307    42283
202403    42258
202306    42155
202305    41949
202401    41877
202404    41810
202302    41749
202304    41691
202312    41674
202308    41650
202309    41574
202311    41564
202303    41481
202301    41062
Name: USE_MON, dtype: int64

In [5]:
date['USE_DT'].value_counts()

20240409    41328
20240419    41315
20240404    41292
20240412    41291
20240425    41289
            ...
20240114    39935
20231217    39934
20240107    39923
20240121    39895
20240210    39716
Name: USE_DT, Length: 182, dtype: int64

In [6]:
date.columns

Index(['USE_DT', 'BUS_ROUTE_ID', 'BUS_ROUTE_NO', 'BUS_ROUTE_NM',
       'STND_BSST_ID', 'BSST_ARS_NO', 'BUS_STA_NM', 'RIDE_PASGR_NUM',
       'ALIGHT_PASGR_NUM', 'WORK_DT'],
      dtype='object')

In [7]:
time.columns

Index(['USE_MON', 'BUS_ROUTE_NO', 'BUS_ROUTE_NM', 'STND_BSST_ID',
       'BSST_ARS_NO', 'BUS_STA_NM', 'MIDNIGHT_RIDE_NUM', 'MIDNIGHT_ALIGHT_NUM',
       'ONE_RIDE_NUM', 'ONE_ALIGHT_NUM', 'TWO_RIDE_NUM', 'TWO_ALIGHT_NUM',
       'THREE_RIDE_NUM', 'THREE_ALIGHT_NUM', 'FOUR_RIDE_NUM',
       'FOUR_ALIGHT_NUM', 'FIVE_RIDE_NUM', 'FIVE_ALIGHT_NUM', 'SIX_RIDE_NUM',
       'SIX_ALIGHT_NUM', 'SEVEN_RIDE_NUM', 'SEVEN_ALIGHT_NUM',
       'EIGHT_RIDE_NUM', 'EIGHT_ALIGHT_NUM', 'NINE_RIDE_NUM',
       'NINE_ALIGHT_NUM', 'TEN_RIDE_NUM', 'TEN_ALIGHT_NUM', 'ELEVEN_RIDE_NUM',
       'ELEVEN_ALIGHT_NUM', 'TWELVE_RIDE_NUM', 'TWELVE_ALIGHT_NUM',
       'THIRTEEN_RIDE_NUM', 'THIRTEEN_ALIGHT_NUM', 'FOURTEEN_RIDE_NUM',
       'FOURTEEN_ALIGHT_NUM', 'FIFTEEN_RIDE_NUM', 'FIFTEEN_ALIGHT_NUM',
       'SIXTEEN_RIDE_NUM', 'SIXTEEN_ALIGHT_NUM', 'SEVENTEEN_RIDE_NUM',
       'SEVENTEEN_ALIGHT_NUM', 'EIGHTEEN_RIDE_NUM', 'EIGHTEEN_ALIGHT_NUM',
       'NINETEEN_RIDE_NUM', 'NINETEEN_ALIGHT_NUM', 'TWENTY_RIDE_NUM',
       'TWENTY_ALIGHT_NUM', 'TWENTY_ONE_RIDE_NUM', 'TWENTY_ONE_ALIGHT_NUM',
       'TWENTY_TWO_RIDE_NUM', 'TWENTY_TWO_ALIGHT_NUM', 'TWENTY_THREE_RIDE_NUM',
       'TWENTY_THREE_ALIGHT_NUM', 'MNTN_TYP_CD', 'MNTN_TYP_NM', 'WORK_DT'],
      dtype='object')

- API로 받아온 getout_bus_by_time_df에는 BUS_ROUTE_ID 가 없음

In [8]:
len(date['BUS_ROUTE_ID'].unique())

668

In [9]:
len(date['BUS_ROUTE_NO'].unique())

649

In [10]:
temp_df = date.loc[:, ['BUS_ROUTE_ID', 'BUS_ROUTE_NO',  'BUS_ROUTE_NM']]

for BUS_ROUTE_ID in temp_df['BUS_ROUTE_ID'].unique():
    temp2_df = temp_df[temp_df['BUS_ROUTE_ID'] == BUS_ROUTE_ID]
    if len(temp2_df['BUS_ROUTE_NM'].unique()) > 1:
        print(temp2_df)

         BUS_ROUTE_ID BUS_ROUTE_NO           BUS_ROUTE_NM
3723         11110053          501         501번(서울대~종로2가)
3724         11110053          501         501번(서울대~종로2가)
3725         11110053          501         501번(서울대~종로2가)
3726         11110053          501         501번(서울대~종로2가)
3727         11110053          501         501번(서울대~종로2가)
...               ...          ...                    ...
7372726      11110053          501  501번(한남운수대학동차고지~종로2가)
7372727      11110053          501  501번(한남운수대학동차고지~종로2가)
7372728      11110053          501  501번(한남운수대학동차고지~종로2가)
7372729      11110053          501  501번(한남운수대학동차고지~종로2가)
7372730      11110053          501  501번(한남운수대학동차고지~종로2가)

[10556 rows x 3 columns]
         BUS_ROUTE_ID BUS_ROUTE_NO      BUS_ROUTE_NM
10258        11110257         5616    5616번(가산동~등촌동)
10259        11110257         5616    5616번(가산동~등촌동)
10260        11110257         5616    5616번(가산동~등촌동)
10261        11110257         5616    5616번(가산동~등촌동)
10262        11110257         5616    5616번(가산동~등촌동)
...               ...          ...               ...
7379328      11110257         5616  5616번(가산동~영도중학교)
7379329      11110257         5616  5616번(가산동~영도중학교)
7379330      11110257         5616  5616번(가산동~영도중학교)
7379331      11110257         5616  5616번(가산동~영도중학교)
7379332      11110257         5616  5616번(가산동~영도중학교)

[21394 rows x 3 columns]
         BUS_ROUTE_ID BUS_ROUTE_NO                BUS_ROUTE_NM
23660        11110599         동작17         동작17(극동아파트~이수힐스테이트)
23661        11110599         동작17         동작17(극동아파트~이수힐스테이트)
23662        11110599         동작17         동작17(극동아파트~이수힐스테이트)
23663        11110599         동작17         동작17(극동아파트~이수힐스테이트)
23664        11110599         동작17         동작17(극동아파트~이수힐스테이트)
...               ...          ...                         ...
7392662      11110599         동작17  동작17(극동아파트~이수힐스테이트.이수푸르지오)
7392663      11110599         동작17  동작17(극동아파트~이수힐스테이트.이수푸르지오)
7392664      11110599         동작17  동작17(극동아파트~이수힐스테이트.이수푸르지오)
7392665      11110599         동작17  동작17(극동아파트~이수힐스테이트.이수푸르지오)
7392666      11110599         동작17  동작17(극동아파트~이수힐스테이트.이수푸르지오)

[4550 rows x 3 columns]
         BUS_ROUTE_ID BUS_ROUTE_NO     BUS_ROUTE_NM
26273        11110712         은평01  은평01(연신내역~그린마트)
26274        11110712         은평01  은평01(연신내역~그린마트)
26275        11110712         은평01  은평01(연신내역~그린마트)
26276        11110712         은평01  은평01(연신내역~그린마트)
26277        11110712         은평01  은평01(연신내역~그린마트)
...               ...          ...              ...
3030171      11110712         은평01   은평01(연신내역~석광사)
3030172      11110712         은평01   은평01(연신내역~석광사)
3030173      11110712         은평01   은평01(연신내역~석광사)
3030174      11110712         은평01   은평01(연신내역~석광사)
3030175      11110712         은평01   은평01(연신내역~석광사)

[600 rows x 3 columns]
         BUS_ROUTE_ID BUS_ROUTE_NO        BUS_ROUTE_NM
26876        11110749        영등포09  영등포09(신도림역~영등포역후문)
26877        11110749        영등포09  영등포09(신도림역~영등포역후문)
26878        11110749        영등포09  영등포09(신도림역~영등포역후문)
26879        11110749        영등포09  영등포09(신도림역~영등포역후문)
26880        11110749        영등포09  영등포09(신도림역~영등포역후문)
...               ...          ...                 ...
7395811      11110749        영등포09    영등포09(신도림역~영등포역)
7395812      11110749        영등포09    영등포09(신도림역~영등포역)
7395813      11110749        영등포09    영등포09(신도림역~영등포역)
7395814      11110749        영등포09    영등포09(신도림역~영등포역)
7395815      11110749        영등포09    영등포09(신도림역~영등포역)

[4732 rows x 3 columns]
         BUS_ROUTE_ID BUS_ROUTE_NO     BUS_ROUTE_NM
31747        11110978         강북04  강북04(연일슈퍼~수유시장)
31748        11110978         강북04  강북04(연일슈퍼~수유시장)
31749        11110978         강북04  강북04(연일슈퍼~수유시장)
31750        11110978         강북04  강북04(연일슈퍼~수유시장)
31751        11110978         강북04  강북04(연일슈퍼~수유시장)
...               ...          ...              ...
7401143      11110978         강북04  강북04(영암마트~수유시장)
7401144      11110978         강북04  강북04(영암마트~수유시장)
7401145      11110978         강북04  강북04(영암마트~수유시장)
7401146      11110978         강북04  강북04(영암마트~수유시장)
7401147      11110978         강북04  강북04(영암마트~수유시장)

[4723 rows x 3 columns]
         BUS_ROUTE_ID BUS_ROUTE_NO                      BUS_ROUTE_NM
37785        41110095       9401-1  9401-1번(이매촌한신.서현역.AK프라자~순천향대학병원)
37786        41110095       9401-1  9401-1번(이매촌한신.서현역.AK프라자~순천향대학병원)
37787        41110095       9401-1  9401-1번(이매촌한신.서현역.AK프라자~순천향대학병원)
37788        41110095       9401-1  9401-1번(이매촌한신.서현역.AK프라자~순천향대학병원)
37789        41110095       9401-1  9401-1번(이매촌한신.서현역.AK프라자~순천향대학병원)
...               ...          ...                               ...
7407196      41110095       9401-1    9401-1번(푸른마을~서울시중부기술교육원.블루스퀘어)
7407197      41110095       9401-1    9401-1번(푸른마을~서울시중부기술교육원.블루스퀘어)
7407198      41110095       9401-1    9401-1번(푸른마을~서울시중부기술교육원.블루스퀘어)
7407199      41110095       9401-1    9401-1번(푸른마을~서울시중부기술교육원.블루스퀘어)
7407200      41110095       9401-1    9401-1번(푸른마을~서울시중부기술교육원.블루스퀘어)

[3081 rows x 3 columns]

In [11]:
date[date['BUS_ROUTE_NO']== '1120']

,USE_DT,BUS_ROUTE_ID,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,RIDE_PASGR_NUM,ALIGHT_PASGR_NUM,WORK_DT
6358,20231101,11110126,1120,1120번(하계동~삼양동입구),108000055,09143,강북노인종합복지관(00034),36,30,20231104
6359,20231101,11110126,1120,1120번(하계동~삼양동입구),109000117,10202,쌍문동우이빌라(00053),12,24,20231104
6360,20231101,11110126,1120,1120번(하계동~삼양동입구),108000165,09253,미아역8번출구.신일중고(00037),5,134,20231104
6361,20231101,11110126,1120,1120번(하계동~삼양동입구),109000128,10213,쌍문동현대.한양아파트(00021),70,122,20231104
6362,20231101,11110126,1120,1120번(하계동~삼양동입구),109000131,10216,도봉구보건소앞(00060),85,45,20231104
...,...,...,...,...,...,...,...,...,...,...
7375387,20240430,11110126,1120,1120번(하계동~삼양동입구),110900079,11563,노원구청앞(00014),530,7,20240503
7375388,20240430,11110126,1120,1120번(하계동~삼양동입구),110900128,11590,상계6동우체국(00067),13,264,20240503
7375389,20240430,11110126,1120,1120번(하계동~삼양동입구),109900046,10747,청구아파트(00056),15,45,20240503
7375390,20240430,11110126,1120,1120번(하계동~삼양동입구),109900076,10564,청구아파트(00023),35,43,20240503
7375391,20240430,11110126,1120,1120번(하계동~삼양동입구),110900079,11563,노원구청앞(00075),53,18,20240503

### time DF 가공하기

- time 수정하기 : 보기편하도록 시간을 숫자로 보기 변하도록 변경함

In [12]:
time_colname_list = ['MIDNIGHT_RIDE_NUM', 'MIDNIGHT_ALIGHT_NUM','ONE_RIDE_NUM', 'ONE_ALIGHT_NUM', 'TWO_RIDE_NUM', 'TWO_ALIGHT_NUM',
       'THREE_RIDE_NUM', 'THREE_ALIGHT_NUM', 'FOUR_RIDE_NUM','FOUR_ALIGHT_NUM', 'FIVE_RIDE_NUM', 'FIVE_ALIGHT_NUM', 'SIX_RIDE_NUM',
       'SIX_ALIGHT_NUM', 'SEVEN_RIDE_NUM', 'SEVEN_ALIGHT_NUM','EIGHT_RIDE_NUM', 'EIGHT_ALIGHT_NUM', 'NINE_RIDE_NUM',
       'NINE_ALIGHT_NUM', 'TEN_RIDE_NUM', 'TEN_ALIGHT_NUM', 'ELEVEN_RIDE_NUM','ELEVEN_ALIGHT_NUM', 'TWELVE_RIDE_NUM', 'TWELVE_ALIGHT_NUM',
       'THIRTEEN_RIDE_NUM', 'THIRTEEN_ALIGHT_NUM', 'FOURTEEN_RIDE_NUM','FOURTEEN_ALIGHT_NUM', 'FIFTEEN_RIDE_NUM', 'FIFTEEN_ALIGHT_NUM',
       'SIXTEEN_RIDE_NUM', 'SIXTEEN_ALIGHT_NUM', 'SEVENTEEN_RIDE_NUM','SEVENTEEN_ALIGHT_NUM', 'EIGHTEEN_RIDE_NUM', 'EIGHTEEN_ALIGHT_NUM',
       'NINETEEN_RIDE_NUM', 'NINETEEN_ALIGHT_NUM', 'TWENTY_RIDE_NUM','TWENTY_ALIGHT_NUM', 'TWENTY_ONE_RIDE_NUM', 'TWENTY_ONE_ALIGHT_NUM',
       'TWENTY_TWO_RIDE_NUM', 'TWENTY_TWO_ALIGHT_NUM', 'TWENTY_THREE_RIDE_NUM','TWENTY_THREE_ALIGHT_NUM']

corrected_colname_list = []
ride_colname_list = []
alight_colname_list = []
for i in range(24):
    corrected_colname_list.append('ride_' + str(i))
    corrected_colname_list.append('alight_' + str(i))
    ride_colname_list.append('ride_' + str(i))
    alight_colname_list.append('alight_' + str(i))

time.rename(columns = dict(zip(time_colname_list, corrected_colname_list)), inplace = True)
time.head(1)

,USE_MON,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,ride_0,alight_0,ride_1,alight_1,...,alight_20,ride_21,alight_21,ride_22,alight_22,ride_23,alight_23,MNTN_TYP_CD,MNTN_TYP_NM,WORK_DT
0,202301,100,100번(하계동~용산구청),110000327,11428,한성여객종점(00001),0,2,0,2,...,0,5,2,3,2,0,0,10,서울간선버스,20230203

In [13]:
time_df = time.copy()

- wide_to_long 함수 : 데이터 프레임을 "wide" 형식에서 "long" 형식으로 변환하는 데 사용

In [14]:
time_df["idx"] = time_df.index
time_df = pd.wide_to_long(time_df, stubnames=['ride', 'alight'], i=['idx'],j='TIME', sep='_')
time_df

,,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,WORK_DT,ride,alight
idx,TIME,,,,,,,,,,,
0,0,100번(하계동~용산구청),10,100,110000327,11428,한성여객종점(00001),서울간선버스,202301,20230203,0,2
1,0,100번(하계동~용산구청),10,100,110000335,11436,하계1동주민센터(00010),서울간선버스,202301,20230203,0,0
2,0,100번(하계동~용산구청),10,100,107000011,08101,숭곡초교입구(00100),서울간선버스,202301,20230203,149,98
3,0,100번(하계동~용산구청),10,100,107000012,08102,창문여고(00101),서울간선버스,202301,20230203,167,220
4,0,100번(하계동~용산구청),10,100,107000013,08103,동방고개(00102),서울간선버스,202301,20230203,11,151
...,...,...,...,...,...,...,...,...,...,...,...,...
669580,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000204,14307,누리꿈스퀘어.MBC(00005),서울지선버스,202404,20240503,0,0
669581,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),서울지선버스,202404,20240503,0,0
669582,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000181,14272,월드컵파크7단지(00007),서울지선버스,202404,20240503,0,0
669583,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000040,16136,가양역.마포중고등학교(00008),서울지선버스,202404,20240503,0,0
669584,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000039,16135,가양역.마포중고등학교(00009),서울지선버스,202404,20240503,0,0

In [15]:
time_df1 = time_df.reset_index()
time_df1.drop(['idx', 'WORK_DT'], axis=1, inplace = True)
time_df1.rename(columns={'ride': 'RIDE_NUM', 'alight': 'ALIGHT_NUM'}, inplace = True)
time_df1

,TIME,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,RIDE_NUM,ALIGHT_NUM
0,0,100번(하계동~용산구청),10,100,110000327,11428,한성여객종점(00001),서울간선버스,202301,0,2
1,0,100번(하계동~용산구청),10,100,110000335,11436,하계1동주민센터(00010),서울간선버스,202301,0,0
2,0,100번(하계동~용산구청),10,100,107000011,08101,숭곡초교입구(00100),서울간선버스,202301,149,98
3,0,100번(하계동~용산구청),10,100,107000012,08102,창문여고(00101),서울간선버스,202301,167,220
4,0,100번(하계동~용산구청),10,100,107000013,08103,동방고개(00102),서울간선버스,202301,11,151
...,...,...,...,...,...,...,...,...,...,...,...
16070035,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000204,14307,누리꿈스퀘어.MBC(00005),서울지선버스,202404,0,0
16070036,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),서울지선버스,202404,0,0
16070037,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000181,14272,월드컵파크7단지(00007),서울지선버스,202404,0,0
16070038,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000040,16136,가양역.마포중고등학교(00008),서울지선버스,202404,0,0
16070039,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000039,16135,가양역.마포중고등학교(00009),서울지선버스,202404,0,0

- 사용년월,노선번호,표준버스정류장ID가 중복되는 경우

In [16]:
temp_grouped = time_df1.groupby(['STND_BSST_ID', 'BUS_ROUTE_NO', 'USE_MON']).size()
temp_grouped.unique() #고유값

array([ 24,  48,  72,  96, 120], dtype=int64)

In [17]:
temp_grouped[temp_grouped == 72]

STND_BSST_ID  BUS_ROUTE_NO  USE_MON
100000053     7212          202306     72
100000054     7212          202306     72
100000059     7212          202306     72
100000150     7212          202306     72
100000181     7212          202306     72
                                       ..
114000219     662           202312     72
114000283     662           202312     72
116000019     6511          202312     72
116000195     N16           202312     72
120000188     5511          202312     72
Length: 630, dtype: int64

In [18]:
temp_grouped[temp_grouped == 120]

STND_BSST_ID  BUS_ROUTE_NO  USE_MON
115900089     강서03          202312     120
~             151           202401     120
dtype: int64

In [19]:
temp_grouped[temp_grouped == 24]

STND_BSST_ID  BUS_ROUTE_NO  USE_MON
100000001     470           202301     24
                            202302     24
                            202303     24
                            202304     24
                            202305     24
                                       ..
999800003     9404          202312     24
999800004     9404          202312     24
999800005     9701          202312     24
              9707          202312     24
~             151           202312     24
Length: 561013, dtype: int64

In [20]:
temp_grouped[temp_grouped == 48]

STND_BSST_ID  BUS_ROUTE_NO  USE_MON
100000001     470           202307     48
              741           202307     48
              N37           202301     48
                            202302     48
                            202303     48
                                       ..
221000085     201           202312     48
990015176     4318          202312     48
998101900     N13           202312     48
998502964     9401-1        202312     48
999033574     7021          202312     48
Length: 52842, dtype: int64

In [21]:
time_df1[ (time_df1['STND_BSST_ID'] == 100000001) &  (time_df1['BUS_ROUTE_NO'] == 'N37')&  (time_df1['USE_MON'] == 202301)]

,TIME,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,RIDE_NUM,ALIGHT_NUM
39515,0,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,21,14
39689,0,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
709100,1,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,163,146
709274,1,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
1378685,2,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,96,85
1378859,2,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,91,72
2048270,3,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
2048444,3,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,186,100
2717855,4,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
2718029,4,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,89,31
3387440,5,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
3387614,5,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
4057025,6,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
4057199,6,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
4726610,7,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
4726784,7,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
5396195,8,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
5396369,8,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
6065780,9,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
6065954,9,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
6735365,10,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
6735539,10,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
7404950,11,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
7405124,11,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
8074535,12,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
8074709,12,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
8744120,13,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
8744294,13,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
9413705,14,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
9413879,14,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
10083290,15,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
10083464,15,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
10752875,16,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
10753049,16,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
11422460,17,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
11422634,17,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
12092045,18,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
12092219,18,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
12761630,19,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
12761804,19,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
13431215,20,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
13431389,20,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
14100800,21,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
14100974,21,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
14770385,22,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
14770559,22,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0
15439970,23,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,0,0
15440144,23,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0

In [22]:
#  cols에 해당하는 값들이 다 같으면 중복으로 간주하고 첫번째 행만 유지
cols = ['TIME', 'BUS_STA_NM', 'BUS_ROUTE_NM', 'STND_BSST_ID', 'BSST_ARS_NO', 'BUS_ROUTE_NO', 'USE_MON']
time_df1 = time_df1.drop_duplicates( cols, keep="first" )
time_df1

,TIME,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,RIDE_NUM,ALIGHT_NUM
0,0,100번(하계동~용산구청),10,100,110000327,11428,한성여객종점(00001),서울간선버스,202301,0,2
1,0,100번(하계동~용산구청),10,100,110000335,11436,하계1동주민센터(00010),서울간선버스,202301,0,0
2,0,100번(하계동~용산구청),10,100,107000011,08101,숭곡초교입구(00100),서울간선버스,202301,149,98
3,0,100번(하계동~용산구청),10,100,107000012,08102,창문여고(00101),서울간선버스,202301,167,220
4,0,100번(하계동~용산구청),10,100,107000013,08103,동방고개(00102),서울간선버스,202301,11,151
...,...,...,...,...,...,...,...,...,...,...,...
16070035,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000204,14307,누리꿈스퀘어.MBC(00005),서울지선버스,202404,0,0
16070036,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),서울지선버스,202404,0,0
16070037,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000181,14272,월드컵파크7단지(00007),서울지선버스,202404,0,0
16070038,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000040,16136,가양역.마포중고등학교(00008),서울지선버스,202404,0,0
16070039,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000039,16135,가양역.마포중고등학교(00009),서울지선버스,202404,0,0

- 총 승차 인원 수를 추가

In [23]:
ride_sum_grouped = time_df1.groupby(['STND_BSST_ID', 'BUS_ROUTE_NO', 'USE_MON']).agg({'RIDE_NUM': 'sum'}) #그룹화하여, ride_num열값을 합산
time_df2 = time_df1.merge(ride_sum_grouped, how='left', on=['STND_BSST_ID', 'BUS_ROUTE_NO', 'USE_MON']) #병합

In [24]:
time_df2[ (time_df1['STND_BSST_ID'] == 100000001) &  (time_df1['BUS_ROUTE_NO'] == 'N37')&  (time_df2['USE_MON'] == 202301)]

C:\Users\haeun\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,TIME,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,RIDE_NUM_x,ALIGHT_NUM,RIDE_NUM_y
39515,0,N37번(송파공영차고지~진관공영차고지),51,N37,100000001,01001,종로2가사거리(00032),서울심야버스,202301,21,14,646
39689,0,N37번(진관공영차고지~송파공영차고지),51,N37,100000001,01001,종로2가사거리(00089),서울심야버스,202301,0,0,646
709100,1,N37번(진관공영차고지~송파공영차고지),51,N37,122000223,23327,군인공제회관(00038),서울심야버스,202301,10,13,34
709274,1,111번(민락동차고지~동대문),10,111,110000080,11180,상계주공9단지(00090),서울간선버스,202301,0,0,683
1378685,2,111번(민락동차고지~동대문),10,111,207000446,61618,양지마을후문입구(00004),서울간선버스,202301,0,0,658
1378859,2,760번(대화동~영등포소방서.타임스퀘어),10,760,219000193,36281,대화역(00100),서울간선버스,202301,2,28,452
2048270,3,4425번(상대원차고지~삼성역),20,4425,122000131,23234,은마파출소(00050),서울지선버스,202301,0,0,1860
2048444,3,6713번(철산동~홍대입구역),20,6713,118000047,19132,국회의사당역.국민은행(00027),서울지선버스,202301,0,0,4863
2717855,4,760번(대화동~영등포소방서.타임스퀘어),10,760,113000021,14111,DMC첨단산업센터(00066),서울간선버스,202301,0,0,1308
2718029,4,강동02(가래여울~암사동서원마을),30,강동02,124900061,25506,강일리버파크3단지301동(00007),서울마을버스,202301,0,0,312
3387440,5,강동02(가래여울~암사동서원마을),30,강동02,124000071,25171,광문고.서울컨벤션고(00019),서울마을버스,202301,0,0,738
3387614,5,"702번(B,용두초교방향,서오릉~종로1가)",10,702B,218000558,35142,기점용두동(00001),서울간선버스,202301,2,0,125
4057025,6,507번(석수역~동대문문화공원),10,507,101000050,02149,명동입구(00049),서울간선버스,202301,20,181,2272
4057199,6,5633번(노온사동~순복음교회),20,5633,213000148,38240,동창골(00004),서울지선버스,202301,3,2,169
4726610,7,"702번(B,용두초교방향,서오릉~종로1가)",10,702B,218000567,35478,용두초등학교입구.금륜사앞(00066),서울간선버스,202301,1,73,69
4726784,7,"661번(부천상동~영등포역,신세계백화점)",10,661,212000055,45028,서림아파트(00033),서울간선버스,202301,266,29,2342
5396195,8,5633번(노온사동~순복음교회),20,5633,213000298,38203,기아자동차후문.한소망교회(00096),서울지선버스,202301,16,83,509
5396369,8,540번(군포공영차고지~강남성모병원),10,540,121000023,22023,구반포역.세화고등학교(00050),서울간선버스,202301,71,14,2423
6065780,9,"661번(부천상동~영등포역,신세계백화점)",10,661,210000367,11181,부천시민회관(00009),서울간선버스,202301,73,9,1079
6065954,9,341번(강동공영차고지~우면동),10,341,123000056,24145,잠실트리지움아파트앞(00072),서울간선버스,202301,72,50,1527
6735365,10,341번(강동공영차고지~우면동),10,341,123000038,24127,몽촌토성역(00021),서울간선버스,202301,31,129,546
6735539,10,"8772번(휴일,구파발~대서문입구)",20,8772,111000150,12229,푸르지오625동앞.관음사입구(00011),서울지선버스,202301,8,9,28
7404950,11,721번(북가좌동~건대입구역),10,721,104000135,05228,서울화양초등학교(00043),서울간선버스,202301,17,318,555
7405124,11,8774번(구산동~서대문구청),20,8774,111000122,12210,신사동고개.은평지역자활센터(00042),서울지선버스,202301,42,38,822
8074535,12,8541번(호압사~강남역),20,8541,121000019,22019,고속터미널(00042),서울지선버스,202301,0,0,310
8744120,13,9714번(교하운정~서울역),50,9714,229001302,30896,물향기마을12단지(00045),서울광역버스,202301,2,37,63
10042086,15,100번(하계동~용산구청),10,100,102000173,03267,서빙고역교차로(00062),서울간선버스,202301,61,37,519
10711497,16,100번(하계동~용산구청),10,100,110000343,11444,하계한신청구아파트(00121),서울간선버스,202301,1,19,2
10711671,16,101번(화계사~동대문),10,101,109900046,10747,청구아파트(00008),서울간선버스,202301,85,44,1777
11381082,17,101번(화계사~동대문),10,101,107000068,08158,안암오거리(00029),서울간선버스,202301,758,296,8035
11381256,17,104번(강북청소년수련관난나~숭례문),10,104,107000008,08008,돈암사거리.성신여대입구(00048),서울간선버스,202301,1275,570,16851
12050667,18,102번(상계동~동대문),10,102,110000145,11245,상계주공2단지(00006),서울간선버스,202301,309,159,5325
12050841,18,106번(의정부~동대문),10,106,207000064,61044,장수원.신한대학교(00016),서울간선버스,202301,213,178,3327
12720252,19,105번(상계동~서울역),10,105,101000046,02145,남대문시장.회현역(00043),서울간선버스,202301,86,135,1825
12720426,19,"110번(A,고려대방향,정릉~정릉)",10,110A,102000092,03186,녹사평역(00041),서울간선버스,202301,154,149,2138
13389837,20,106번(의정부~동대문),10,106,109000002,10002,도봉산역(00072),서울간선버스,202301,897,127,10984
13390011,20,130번(우이동~길동),10,130,107000061,08151,종암사거리입구(00069),서울간선버스,202301,493,412,8297
14059422,21,130번(우이동~길동),10,130,108000005,09005,수유시장.성신여대미아캠퍼스앞(00018),서울간선버스,202301,341,201,12421
14059596,21,141번(도봉산~염곡동),10,141,109000015,10015,쌍문역(00011),서울간선버스,202301,150,151,6092
14729007,22,140번(도봉산역~AT센터),10,140,121000219,22295,언남고교(00045),서울간선버스,202301,147,9,5149
14729181,22,142번(도봉동~고속터미널),10,142,107000007,08007,돈암사거리.성신여대입구(00022),서울간선버스,202301,479,112,6701
15398592,23,141번(도봉산~염곡동),10,141,122000040,23140,임피리얼팰리스호텔.팬트힐루논현(00068),서울간선버스,202301,114,81,3151
15398766,23,143번(정릉~개포동),10,143,121000302,22381,반포대교남단 한강시민공원입구(00027),서울간선버스,202301,0,7,232

In [25]:
#승차 인원이 그룹 내 전체 승차 인원에서 차지하는 비율을 계산
time_df2['RIDE_PCT'] = round(time_df2['RIDE_NUM_x'] / time_df2['RIDE_NUM_y'], 4)
time_df2

,TIME,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,RIDE_NUM_x,ALIGHT_NUM,RIDE_NUM_y,RIDE_PCT
0,0,100번(하계동~용산구청),10,100,110000327,11428,한성여객종점(00001),서울간선버스,202301,0,2,339,0.0000
1,0,100번(하계동~용산구청),10,100,110000335,11436,하계1동주민센터(00010),서울간선버스,202301,0,0,3579,0.0000
2,0,100번(하계동~용산구청),10,100,107000011,08101,숭곡초교입구(00100),서울간선버스,202301,149,98,4601,0.0324
3,0,100번(하계동~용산구청),10,100,107000012,08102,창문여고(00101),서울간선버스,202301,167,220,6874,0.0243
4,0,100번(하계동~용산구청),10,100,107000013,08103,동방고개(00102),서울간선버스,202301,11,151,1467,0.0075
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067203,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000204,14307,누리꿈스퀘어.MBC(00005),서울지선버스,202404,0,0,1003,0.0000
16067204,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),서울지선버스,202404,0,0,1644,0.0000
16067205,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000181,14272,월드컵파크7단지(00007),서울지선버스,202404,0,0,2526,0.0000
16067206,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000040,16136,가양역.마포중고등학교(00008),서울지선버스,202404,0,0,529,0.0000
16067207,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000039,16135,가양역.마포중고등학교(00009),서울지선버스,202404,0,0,5354,0.0000

In [26]:
#하차 인원이 그룹 내 전체 인원에서 차지하는 비율을 계산
alight_sum_grouped = time_df1.groupby(['STND_BSST_ID', 'BUS_ROUTE_NO', 'USE_MON']).agg({'ALIGHT_NUM': 'sum'})
time_df2 = time_df2.merge(alight_sum_grouped, how='left', on=['STND_BSST_ID', 'BUS_ROUTE_NO', 'USE_MON'])
time_df2['ALIGHT_PCT'] = round(time_df2['ALIGHT_NUM_x'] / time_df2['ALIGHT_NUM_y'], 4)
time_df2

,TIME,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,RIDE_NUM_x,ALIGHT_NUM_x,RIDE_NUM_y,RIDE_PCT,ALIGHT_NUM_y,ALIGHT_PCT
0,0,100번(하계동~용산구청),10,100,110000327,11428,한성여객종점(00001),서울간선버스,202301,0,2,339,0.0000,42,0.0476
1,0,100번(하계동~용산구청),10,100,110000335,11436,하계1동주민센터(00010),서울간선버스,202301,0,0,3579,0.0000,670,0.0000
2,0,100번(하계동~용산구청),10,100,107000011,08101,숭곡초교입구(00100),서울간선버스,202301,149,98,4601,0.0324,4335,0.0226
3,0,100번(하계동~용산구청),10,100,107000012,08102,창문여고(00101),서울간선버스,202301,167,220,6874,0.0243,6194,0.0355
4,0,100번(하계동~용산구청),10,100,107000013,08103,동방고개(00102),서울간선버스,202301,11,151,1467,0.0075,2225,0.0679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067203,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000204,14307,누리꿈스퀘어.MBC(00005),서울지선버스,202404,0,0,1003,0.0000,1243,0.0000
16067204,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),서울지선버스,202404,0,0,1644,0.0000,1140,0.0000
16067205,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000181,14272,월드컵파크7단지(00007),서울지선버스,202404,0,0,2526,0.0000,177,0.0000
16067206,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000040,16136,가양역.마포중고등학교(00008),서울지선버스,202404,0,0,529,0.0000,6537,0.0000
16067207,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000039,16135,가양역.마포중고등학교(00009),서울지선버스,202404,0,0,5354,0.0000,52,0.0000

In [27]:
#하루동안 0이라 NAN값 나오는 것들 처리
print(time_df2.isnull().sum())
time_df2['RIDE_PCT'] = time_df2['RIDE_PCT'].fillna(0)
time_df2['ALIGHT_PCT'] = time_df2['ALIGHT_PCT'].fillna(0)
print(time_df2.isnull().sum())

TIME                0
BUS_ROUTE_NM        0
MNTN_TYP_CD         0
BUS_ROUTE_NO        0
STND_BSST_ID        0
BSST_ARS_NO         0
BUS_STA_NM          0
MNTN_TYP_NM         0
USE_MON             0
RIDE_NUM_x          0
ALIGHT_NUM_x        0
RIDE_NUM_y          0
RIDE_PCT        83976
ALIGHT_NUM_y        0
ALIGHT_PCT      28656
dtype: int64
TIME            0
BUS_ROUTE_NM    0
MNTN_TYP_CD     0
BUS_ROUTE_NO    0
STND_BSST_ID    0
BSST_ARS_NO     0
BUS_STA_NM      0
MNTN_TYP_NM     0
USE_MON         0
RIDE_NUM_x      0
ALIGHT_NUM_x    0
RIDE_NUM_y      0
RIDE_PCT        0
ALIGHT_NUM_y    0
ALIGHT_PCT      0
dtype: int64

In [28]:
# col 이름 바꿔주기
col_dict = {'RIDE_NUM_x': 'RIDE_NUM', 'ALIGHT_NUM_x': 'ALIGHT_NUM', 'RIDE_NUM_y': 'RIDE_SUM', 'ALIGHT_NUM_y': 'ALIGHT_SUM'}
time_df2.rename(columns=col_dict, inplace=True)
time_df2

,TIME,BUS_ROUTE_NM,MNTN_TYP_CD,BUS_ROUTE_NO,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,MNTN_TYP_NM,USE_MON,RIDE_NUM,ALIGHT_NUM,RIDE_SUM,RIDE_PCT,ALIGHT_SUM,ALIGHT_PCT
0,0,100번(하계동~용산구청),10,100,110000327,11428,한성여객종점(00001),서울간선버스,202301,0,2,339,0.0000,42,0.0476
1,0,100번(하계동~용산구청),10,100,110000335,11436,하계1동주민센터(00010),서울간선버스,202301,0,0,3579,0.0000,670,0.0000
2,0,100번(하계동~용산구청),10,100,107000011,08101,숭곡초교입구(00100),서울간선버스,202301,149,98,4601,0.0324,4335,0.0226
3,0,100번(하계동~용산구청),10,100,107000012,08102,창문여고(00101),서울간선버스,202301,167,220,6874,0.0243,6194,0.0355
4,0,100번(하계동~용산구청),10,100,107000013,08103,동방고개(00102),서울간선버스,202301,11,151,1467,0.0075,2225,0.0679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067203,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000204,14307,누리꿈스퀘어.MBC(00005),서울지선버스,202404,0,0,1003,0.0000,1243,0.0000
16067204,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),서울지선버스,202404,0,0,1644,0.0000,1140,0.0000
16067205,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,113000181,14272,월드컵파크7단지(00007),서울지선버스,202404,0,0,2526,0.0000,177,0.0000
16067206,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000040,16136,가양역.마포중고등학교(00008),서울지선버스,202404,0,0,529,0.0000,6537,0.0000
16067207,23,8762번(디지털미디어시티역~가양역.마포중고등학교),20,8762,115000039,16135,가양역.마포중고등학교(00009),서울지선버스,202404,0,0,5354,0.0000,52,0.0000

In [29]:
# col 순서 정리
cols = ['BUS_ROUTE_NO', 'BUS_ROUTE_NM', 
        'STND_BSST_ID', 'BSST_ARS_NO', 'BUS_STA_NM',
        'USE_MON', 'TIME',
        'RIDE_NUM', 'RIDE_PCT',	'ALIGHT_NUM', 'ALIGHT_PCT', 'RIDE_SUM', 'ALIGHT_SUM']  #  'RIDE_SUM', 'ALIGHT_SUM'
time_df2 = time_df2[cols]
time_df2

,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,USE_MON,TIME,RIDE_NUM,RIDE_PCT,ALIGHT_NUM,ALIGHT_PCT,RIDE_SUM,ALIGHT_SUM
0,100,100번(하계동~용산구청),110000327,11428,한성여객종점(00001),202301,0,0,0.0000,2,0.0476,339,42
1,100,100번(하계동~용산구청),110000335,11436,하계1동주민센터(00010),202301,0,0,0.0000,0,0.0000,3579,670
2,100,100번(하계동~용산구청),107000011,08101,숭곡초교입구(00100),202301,0,149,0.0324,98,0.0226,4601,4335
3,100,100번(하계동~용산구청),107000012,08102,창문여고(00101),202301,0,167,0.0243,220,0.0355,6874,6194
4,100,100번(하계동~용산구청),107000013,08103,동방고개(00102),202301,0,11,0.0075,151,0.0679,1467,2225
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067203,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000204,14307,누리꿈스퀘어.MBC(00005),202404,23,0,0.0000,0,0.0000,1003,1243
16067204,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),202404,23,0,0.0000,0,0.0000,1644,1140
16067205,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000181,14272,월드컵파크7단지(00007),202404,23,0,0.0000,0,0.0000,2526,177
16067206,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000040,16136,가양역.마포중고등학교(00008),202404,23,0,0.0000,0,0.0000,529,6537
16067207,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000039,16135,가양역.마포중고등학교(00009),202404,23,0,0.0000,0,0.0000,5354,52

In [30]:
time_df2.to_csv('preproccessed_bus_by_time.csv', index=False)

## date data 가공하기

In [33]:
date_df = date.copy()
date_df.drop(['WORK_DT'], axis=1, inplace=True)
date_df.head()

,USE_DT,BUS_ROUTE_ID,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,RIDE_PASGR_NUM,ALIGHT_PASGR_NUM
0,20231101,11110001,100,100번(하계동~용산구청),100000003,01003,명륜3가.성대입구(00030),176,185
1,20231101,11110001,100,100번(하계동~용산구청),101000057,02156,을지로입구.로얄호텔(00079),171,148
2,20231101,11110001,100,100번(하계동~용산구청),101000060,02159,을지로2가.파인에빈뉴(00080),236,98
3,20231101,11110001,100,100번(하계동~용산구청),102000173,03267,서빙고역교차로(00062),42,32
4,20231101,11110001,100,100번(하계동~용산구청),101000061,02160,을지로3가(00035),95,341

In [34]:
date_df['USE_DT'] = pd.to_datetime(date_df['USE_DT'], format='%Y%m%d', errors='raise')
date_df['WEEKDAY'] = date_df['USE_DT'].dt.weekday
date_df

,USE_DT,BUS_ROUTE_ID,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,RIDE_PASGR_NUM,ALIGHT_PASGR_NUM,WEEKDAY
0,2023-11-01,11110001,100,100번(하계동~용산구청),100000003,01003,명륜3가.성대입구(00030),176,185,2
1,2023-11-01,11110001,100,100번(하계동~용산구청),101000057,02156,을지로입구.로얄호텔(00079),171,148,2
2,2023-11-01,11110001,100,100번(하계동~용산구청),101000060,02159,을지로2가.파인에빈뉴(00080),236,98,2
3,2023-11-01,11110001,100,100번(하계동~용산구청),102000173,03267,서빙고역교차로(00062),42,32,2
4,2023-11-01,11110001,100,100번(하계동~용산구청),101000061,02160,을지로3가(00035),95,341,2
...,...,...,...,...,...,...,...,...,...,...
7410223,2024-04-30,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000180,14271,월드컵파크7단지(00010),13,72,1
7410224,2024-04-30,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000202,14296,디지털미디어시티역2번출구(00001),127,0,1
7410225,2024-04-30,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000204,14307,누리꿈스퀘어.MBC(00005),62,40,1
7410226,2024-04-30,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000450,14359,공항철도디지털미디어시티역(00015),0,77,1
7410227,2024-04-30,91000044,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000452,14357,SBS.YTN(00014),25,36,1

In [35]:
# col 이름 바꿔주기
col_dict = {'RIDE_PASGR_NUM': 'RIDE_NUM', 'ALIGHT_PASGR_NUM': 'ALIGHT_NUM'}
date_df.rename(columns=col_dict, inplace=True)

In [36]:
# col 순서 정리
cols = ['BUS_ROUTE_NO', 'BUS_ROUTE_NM', 'BUS_ROUTE_ID',
        'STND_BSST_ID', 'BSST_ARS_NO', 'BUS_STA_NM',
        'USE_DT', 'WEEKDAY',
        'RIDE_NUM', 'ALIGHT_NUM']
date_df = date_df[cols]
date_df

,BUS_ROUTE_NO,BUS_ROUTE_NM,BUS_ROUTE_ID,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,USE_DT,WEEKDAY,RIDE_NUM,ALIGHT_NUM
0,100,100번(하계동~용산구청),11110001,100000003,01003,명륜3가.성대입구(00030),2023-11-01,2,176,185
1,100,100번(하계동~용산구청),11110001,101000057,02156,을지로입구.로얄호텔(00079),2023-11-01,2,171,148
2,100,100번(하계동~용산구청),11110001,101000060,02159,을지로2가.파인에빈뉴(00080),2023-11-01,2,236,98
3,100,100번(하계동~용산구청),11110001,102000173,03267,서빙고역교차로(00062),2023-11-01,2,42,32
4,100,100번(하계동~용산구청),11110001,101000061,02160,을지로3가(00035),2023-11-01,2,95,341
...,...,...,...,...,...,...,...,...,...,...
7410223,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),91000044,113000180,14271,월드컵파크7단지(00010),2024-04-30,1,13,72
7410224,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),91000044,113000202,14296,디지털미디어시티역2번출구(00001),2024-04-30,1,127,0
7410225,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),91000044,113000204,14307,누리꿈스퀘어.MBC(00005),2024-04-30,1,62,40
7410226,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),91000044,113000450,14359,공항철도디지털미디어시티역(00015),2024-04-30,1,0,77
7410227,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),91000044,113000452,14357,SBS.YTN(00014),2024-04-30,1,25,36

In [37]:
date_df.to_csv('preprocessed_bus_by_date.csv', index=False)

### 두 데이터 연결하기

In [18]:
import pandas as pd

# 파일 경로
file1 = "preprocessed_bus_by_date.csv"
file2 = "preprocessed_bus_by_time.csv"

# CSV 파일 불러오기
date = pd.read_csv(file1)
time = pd.read_csv(file2)

import pandas as pd

# 파일 경로
date_file = "date_dataset.csv"
time_file = "time_dataset.csv"
# CSV 파일 불러오기
date = pd.read_csv(date_file)
time = pd.read_csv(time_file)

FileNotFoundError: [Errno 2] No such file or directory: 'preprocessed_bus_by_date.csv'