### 두 데이터 연결하기

In [1]:
import pandas as pd
import numpy as np

file_path1 = "preprocessed_bus_by_date.csv"
file_path2 = "preprocessed_bus_by_time.csv"

date_df = pd.read_csv(file_path1)
time_df = pd.read_csv(file_path2)

C:\Users\haeun\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

- 메모리 사용을 최적화 : 각 열의 데이터 타입을 가능한 가장 작은 크기로 변환

In [2]:
import numpy as np
import pandas as pd

def getOptColDtype(df, col):
    col_dtype = df[col].dtype
    col_max = df[col].max()
    col_min = df[col].min()
    
    if np.issubdtype(col_dtype, np.integer):
        dtype_list = [np.dtype('int8'), np.dtype('int16'), np.dtype('int32'), np.dtype('int64')]
        dtype_info_func = np.iinfo
    
    elif np.issubdtype(col_dtype, np.floating):
        dtype_list = [np.dtype('float16'), np.dtype('float32'), np.dtype('float64')]
        dtype_info_func = np.finfo

    if col_dtype in dtype_list:
        check_count = dtype_list.index(col_dtype)
        
        for idx, dtype in enumerate(dtype_list[:check_count]):
            # update dtype if min/max within smaller dtype
            if (col_max <= dtype_info_func(dtype).max) and (col_min >= dtype_info_func(dtype).min):
                col_dtype = dtype
                break
    
    return col_dtype

def getOptColDict(df):
    col_dtype_dict = {}

    # get non-numeric column names
    nonnum_cols = df[df.select_dtypes(exclude=['number']).columns].columns
    for nonnum_col in nonnum_cols:
        col_dtype_dict[nonnum_col] = df[nonnum_col].dtype

    # get numeric column names
    num_cols = df[df.select_dtypes(include=['number']).columns].columns

    for num_col in num_cols:
        col_dtype_dict[num_col] = getOptColDtype(df, num_col)

    return col_dtype_dict

# Example usage:
# Ensure time_df is defined and is a DataFrame
# time_df = pd.DataFrame({...}) # Your DataFrame definition

time_df = time_df.astype(getOptColDict(time_df))
time_df.rename(columns={'RIDE_NUM': 'RIDE_MONTH_NUM', 'ALIGHT_NUM': 'ALIGHT_MONTH_NUM'}, inplace=True)
time_df

,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,USE_MON,TIME,RIDE_MONTH_NUM,RIDE_PCT,ALIGHT_MONTH_NUM,ALIGHT_PCT,RIDE_SUM,ALIGHT_SUM
0,100,100번(하계동~용산구청),110000327,11428,한성여객종점(00001),202301,0,0,0.000000,2,0.047607,339,42
1,100,100번(하계동~용산구청),110000335,11436,하계1동주민센터(00010),202301,0,0,0.000000,0,0.000000,3579,670
2,100,100번(하계동~용산구청),107000011,08101,숭곡초교입구(00100),202301,0,149,0.032410,98,0.022598,4601,4335
3,100,100번(하계동~용산구청),107000012,08102,창문여고(00101),202301,0,167,0.024307,220,0.035492,6874,6194
4,100,100번(하계동~용산구청),107000013,08103,동방고개(00102),202301,0,11,0.007500,151,0.067871,1467,2225
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067203,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000204,14307,누리꿈스퀘어.MBC(00005),202404,23,0,0.000000,0,0.000000,1003,1243
16067204,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),202404,23,0,0.000000,0,0.000000,1644,1140
16067205,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000181,14272,월드컵파크7단지(00007),202404,23,0,0.000000,0,0.000000,2526,177
16067206,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000040,16136,가양역.마포중고등학교(00008),202404,23,0,0.000000,0,0.000000,529,6537
16067207,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000039,16135,가양역.마포중고등학교(00009),202404,23,0,0.000000,0,0.000000,5354,52

In [3]:
time_df = time_df.astype(getOptColDict(time_df))
time_df.rename(columns={'RIDE_NUM': 'RIDE_MONTH_NUM',
                                          'ALIGHT_NUM': 'ALIGHT_MONTH_NUM'}, inplace=True)
time_df

,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,USE_MON,TIME,RIDE_MONTH_NUM,RIDE_PCT,ALIGHT_MONTH_NUM,ALIGHT_PCT,RIDE_SUM,ALIGHT_SUM
0,100,100번(하계동~용산구청),110000327,11428,한성여객종점(00001),202301,0,0,0.000000,2,0.047607,339,42
1,100,100번(하계동~용산구청),110000335,11436,하계1동주민센터(00010),202301,0,0,0.000000,0,0.000000,3579,670
2,100,100번(하계동~용산구청),107000011,08101,숭곡초교입구(00100),202301,0,149,0.032410,98,0.022598,4601,4335
3,100,100번(하계동~용산구청),107000012,08102,창문여고(00101),202301,0,167,0.024307,220,0.035492,6874,6194
4,100,100번(하계동~용산구청),107000013,08103,동방고개(00102),202301,0,11,0.007500,151,0.067871,1467,2225
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067203,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000204,14307,누리꿈스퀘어.MBC(00005),202404,23,0,0.000000,0,0.000000,1003,1243
16067204,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),202404,23,0,0.000000,0,0.000000,1644,1140
16067205,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000181,14272,월드컵파크7단지(00007),202404,23,0,0.000000,0,0.000000,2526,177
16067206,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000040,16136,가양역.마포중고등학교(00008),202404,23,0,0.000000,0,0.000000,529,6537
16067207,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000039,16135,가양역.마포중고등학교(00009),202404,23,0,0.000000,0,0.000000,5354,52

In [4]:
time_df.columns

Index(['BUS_ROUTE_NO', 'BUS_ROUTE_NM', 'STND_BSST_ID', 'BSST_ARS_NO',
       'BUS_STA_NM', 'USE_MON', 'TIME', 'RIDE_MONTH_NUM', 'RIDE_PCT',
       'ALIGHT_MONTH_NUM', 'ALIGHT_PCT', 'RIDE_SUM', 'ALIGHT_SUM'],
      dtype='object')

In [5]:
#time_df = time_df.drop(columns=['RIDE_PCT', 'ALIGHT_PCT'])
#time_df

,BUS_ROUTE_NO,BUS_ROUTE_NM,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,USE_MON,TIME,RIDE_MONTH_NUM,ALIGHT_MONTH_NUM,RIDE_SUM,ALIGHT_SUM
0,100,100번(하계동~용산구청),110000327,11428,한성여객종점(00001),202301,0,0,2,339,42
1,100,100번(하계동~용산구청),110000335,11436,하계1동주민센터(00010),202301,0,0,0,3579,670
2,100,100번(하계동~용산구청),107000011,08101,숭곡초교입구(00100),202301,0,149,98,4601,4335
3,100,100번(하계동~용산구청),107000012,08102,창문여고(00101),202301,0,167,220,6874,6194
4,100,100번(하계동~용산구청),107000013,08103,동방고개(00102),202301,0,11,151,1467,2225
...,...,...,...,...,...,...,...,...,...,...,...
16067203,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000204,14307,누리꿈스퀘어.MBC(00005),202404,23,0,0,1003,1243
16067204,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000194,14288,월드컵파크5단지.상암중고등학교입구(00006),202404,23,0,0,1644,1140
16067205,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),113000181,14272,월드컵파크7단지(00007),202404,23,0,0,2526,177
16067206,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000040,16136,가양역.마포중고등학교(00008),202404,23,0,0,529,6537
16067207,8762,8762번(디지털미디어시티역~가양역.마포중고등학교),115000039,16135,가양역.마포중고등학교(00009),202404,23,0,0,5354,52

In [6]:
date_df = date_df.astype(getOptColDict(date_df))
date_df

,BUS_ROUTE_NO,BUS_ROUTE_NM,BUS_ROUTE_ID,STND_BSST_ID,BSST_ARS_NO,BUS_STA_NM,USE_DT,WEEKDAY,RIDE_NUM,ALIGHT_NUM
0,100,100번(하계동~용산구청),11110001.0,100000000.0,01003,명륜3가.성대입구(00030),2023-11-01,2.0,176.0,185.0
1,100,100번(하계동~용산구청),11110001.0,101000056.0,02156,을지로입구.로얄호텔(00079),2023-11-01,2.0,171.0,148.0
2,100,100번(하계동~용산구청),11110001.0,101000064.0,02159,을지로2가.파인에빈뉴(00080),2023-11-01,2.0,236.0,98.0
3,100,100번(하계동~용산구청),11110001.0,102000176.0,03267,서빙고역교차로(00062),2023-11-01,2.0,42.0,32.0
4,100,100번(하계동~용산구청),11110001.0,101000064.0,02160,을지로3가(00035),2023-11-01,2.0,95.0,341.0
...,...,...,...,...,...,...,...,...,...,...
909004,N61,N61번(상계동차고지~양천공영차고지),11110370.0,120000024.0,21126,남서울농협남현동지점(00121),2023-11-23,3.0,21.0,3.0
909005,N61,N61번(상계동차고지~양천공영차고지),11110370.0,119000048.0,20141,사당1동관악시장앞(00068),2023-11-23,3.0,25.0,18.0
909006,N61,N61번(상계동차고지~양천공영차고지),11110370.0,119000048.0,20142,예술인마을(00069),2023-11-23,3.0,1.0,10.0
909007,N61,N61번(상계동차고지~양천공영차고지),11110370.0,120000000.0,21102,낙성대입구(00071),2023-11-23,3.0,1.0,11.0
909008,N61,N61번(상계동차고지~,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
date_df.columns

Index(['BUS_ROUTE_NO', 'BUS_ROUTE_NM', 'BUS_ROUTE_ID', 'STND_BSST_ID',
       'BSST_ARS_NO', 'BUS_STA_NM', 'USE_DT', 'WEEKDAY', 'RIDE_NUM',
       'ALIGHT_NUM'],
      dtype='object')

- 우선 단순히 한달 동일하다고 생각하고 연결하기

In [8]:
bus_df = date_df.merge(time_df[['BUS_ROUTE_NO', 'STND_BSST_ID', 'USE_MON', 'TIME', 'RIDE_MONTH_NUM', 'RIDE_PCT', 'ALIGHT_MONTH_NUM', 'ALIGHT_PCT']],
                                                     how='left', 
                                                     on=['BUS_ROUTE_NO', 'STND_BSST_ID'])
bus_df

KeyError: "['RIDE_PCT', 'ALIGHT_PCT'] not in index"